image: 
  file: .gitpod.DockerFile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: 'composer create-project laravel/laravel laravel'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
# List the extensions 
vscode: 
 extensions:
   - felixbecker.php-debug